attention_dropout: 0.1
batch_size: 64
betas:
- 0.9
- 0.999
checkpoints_path: /home/dong/LRL/dclaw/model_DT_DClaw/halfcheetah-medium-v2-DClawTurnFixedT0-v0-932ead79
clip_grad: 0.25
deterministic_torch: false
device: cuda
embedding_dim: 1024
embedding_dropout: 0.1
env_name: DClawTurnFixedT0-v0
episode_len: 300
eval_episodes: 1
eval_every: 1000
eval_seed: 10
group: Gym-MuJoCo
learning_rate: 0.0001
max_action: 1.0
name: halfcheetah-medium-v2-DClawTurnFixedT0-v0-932ead79
num_heads: 1
num_layers: 24
num_samples: 1000
num_workers: 4
project: D-RWKV
residual_dropout: 0.1
reward_scale: 1
seq_len: 20
train_seed: 10
update_steps: 3000
warmup_steps: 1000
weight_decay: 0.0001
